version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-06-13T22-53-53Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: woodzy
    MINIO_ROOT_PASSWORD: skdjal10
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - /data/mirror/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /data/minio/data1-1
      o: bind
  data1-2:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /data/mirror/minio/data1-2
      o: bind
  data2-1:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /data/minio/data2-1
      o: bind
  data2-2:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /data/mirror/minio/data2-2
      o: bind
  data3-1:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /data/minio/data3-1
      o: bind
  data3-2:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /data/mirror/minio/data3-2
      o: bind
  data4-1:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /data/minio/data4-1
      o: bind
  data4-2:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /data/mirror/minio/data4-2
      o: bind
